// Code generated by mockery v2.6.0. DO NOT EDIT.

package mocks

import (
	foaasapi "github.com/jgarrone/foaas-limiting/services/foaasapi"
	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// GetMessageFor provides a mock function with given fields: username
func (_m *Service) GetMessageFor(username string) (*foaasapi.Response, error) {
	ret := _m.Called(username)

	var r0 *foaasapi.Response
	if rf, ok := ret.Get(0).(func(string) *foaasapi.Response); ok {
		r0 = rf(username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*foaasapi.Response)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
